Repository devilery/fds-dev, pull requests merged in 2019-12, with the labels that each got.

#42 Travis
  .travis.yml
  package.json
Labels: size/XS

#55 TEST PR
  README.md
Labels: size/XS

#57 TEST
  README.md
Labels: size/XS

#58 TEST
  .circleci/config.yml
  README.md
Labels: size/XS

#59 Update README.md
  README.md
Labels: size/XS

#60 Update README.md
  README.md
Labels: size/XS

#61 Add Circle approval steps
  .circleci/config.yml
Labels: size/S

#65 fix invite flow
  src/api/test.ts
  src/entity/CustomEntity.ts
  src/entity/GithubUser.ts
  src/entity/index.ts
  src/oauth-github.ts
Labels: size/M

#63 Request context
  package.json
  src/api/slack-interactive-endpoint.ts
  src/index.ts
  src/libs/github.ts
  src/libs/slack-events.js
  yarn.lock
Labels: size/L

#64 Homepage
  src/libs/slack-events.js
Labels: size/S
