Repository devilery/fds-dev, pull requests merged in 2020-01, with the labels that each got.

#70 test-pr-101
  README.md
Labels: size/XS

#68 Pipeline improvements
  package.json
  src/api/test.ts
  src/entity/Commit.ts
  src/entity/CommitCheck.ts
  src/entity/CustomEntity.ts
  src/entity/Pipeline.ts
  src/entity/PullRequest.ts
  src/entity/index.ts
  src/events/types.d.ts
  src/index.ts
  src/libs/circleci-api.ts
  src/libs/circleci.ts
  src/libs/db.ts
  src/libs/event.js
  src/libs/github.ts
  src/libs/http-debug.ts
  src/libs/pr.ts
  src/libs/slack-commands.js
  src/libs/slack-events.js
  src/libs/slack-messages.ts
  src/libs/slack.ts
  src/subscribers/pr.ts
  yarn.lock
Labels: size/XL

#69 Create test fikle
  test fikle
Labels: size/XS

#73 Create asxxx xc
  asxxx xc
Labels: size/XS

#89 Mixpanel
  src/api/slack-interactive-endpoint.ts
  src/index.ts
  src/libs/analytics.ts
  src/libs/http-debug.ts
  src/subscribers/pr.ts
  src/subscribers/slack.ts
Labels: size/L

#109 update
  src/libs/github.ts
  src/libs/pr.ts
  src/libs/slack-messages.ts
  src/libs/slack.ts
  src/subscribers/pr.ts
Labels: size/M
